---
engines:
  duplication:
    enabled: true
    checks:
      Similar code:
        enabled: false
  config:
    languages:
    - javascript
  eslint:
    enabled: true
    exclude_fingerprints:
    - a903bf364dfc9d51652ca69732a2c072
  fixme:
    enabled: true
ratings:
  paths:
  - "**.inc"
  - "**.js"
  - "**.jsx"
  - "**.module"
  - "**.php"
  - "**.py"
  - "**.rb"
exclude_paths:
- test/
